### ISSUE TITLE
Tracking who leaves clan chat

### ISSUE THREAD

**Issue by Elemuts** [fatfingers23/trackscape-discord-bot#22]
Hello, would be perfect to see who leaves clan chat, so i could kick from discord too. Because i have private clan and it would be easier to track. 
Thank you for this discord bot, it helps a lot for clans.

**Comment by fatfingers23** [comment]
I'm glad you are enjoying the discord bot! It should now send broadcasts for when a clanmate leaves the clan as well as when an expulsion happens!

This was closed in #23
