### ISSUE TITLE
Move regex compiling from methods

### ISSUE THREAD

**Issue by fatfingers23** [fatfingers23/trackscape-discord-bot#43]
Need to remove the recompiling of regexs in methods like [this](https://github.com/fatfingers23/trackscape-discord-bot/blob/5f6bbcaa1d12830d8cb8f8effaa3904acd912a23/trackscape-discord-shared/src/osrs_broadcast_extractor.rs#L353C1-L353C186).  Some possible solutions and explanation. 
https://docs.rs/regex/latest/regex/#avoid-re-compiling-regexes-especially-in-a-loop

**Comment by inyourface34456** [comment]
i can help with this

**Comment by fatfingers23** [comment]
Fixed in #47
